In [3]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
cv = CountVectorizer()
tfidf = TfidfVectorizer(max_features=3000)

In [4]:
import pandas as pd

In [8]:
df = pd.read_csv('data/transformed_data_subset.csv',encoding='ISO-8859-1')

In [9]:
df

target                                               text  \
0          0  Go until jurong point, crazy.. Available only ...   
1          0                      Ok lar... Joking wif u oni...   
2          1  Free entry in 2 a wkly comp to win FA Cup fina...   
3          0  U dun say so early hor... U c already then say...   
4          0  Nah I don't think he goes to usf, he lives aro...   
...      ...                                                ...   
5164       1  This is the 2nd time we have tried 2 contact u...   
5165       0             Will Ì_ b going to esplanade fr home?   
5166       0  Pity, * was in mood for that. So...any other s...   
5167       0  The guy did some bitching but I acted like i'd...   
5168       0                         Rofl. Its true to its name   

                                       transformed_text  
0     go jurong point crazi avail bugi n great world...  
1                                 ok lar joke wif u oni  
2     free entri 2 wkli comp win fa cup final tkt 21...  
3                   u dun say earli hor u c alreadi say  
4                  nah think goe usf live around though  
...                                                 ...  
5164  2nd time tri 2 contact u pound prize 2 claim e...  
5165                              b go esplanad fr home  
5166                                  piti mood suggest  
5167  guy bitch act like interest buy someth els nex...  
5168                                     rofl true name  

[5169 rows x 3 columns]

In [12]:
df['transformed_text'].isnull().sum()

np.int64(9)

In [13]:
df['transformed_text'] = df['transformed_text'].fillna('')


In [14]:
X = tfidf.fit_transform(df['transformed_text']).toarray()

In [15]:
X.shape

(5169, 3000)

In [16]:
y = df['target'].values

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [19]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score

In [20]:
gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

In [21]:
gnb.fit(X_train,y_train)
y_pred1 = gnb.predict(X_test)
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(precision_score(y_test,y_pred1))

0.8713733075435203
[[788 108]
 [ 25 113]]
0.5113122171945701


In [22]:
mnb.fit(X_train,y_train)
y_pred2 = mnb.predict(X_test)
print(accuracy_score(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))
print(precision_score(y_test,y_pred2))

0.9709864603481625
[[896   0]
 [ 30 108]]
1.0


In [23]:
bnb.fit(X_train,y_train)
y_pred3 = bnb.predict(X_test)
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(precision_score(y_test,y_pred3))

0.9835589941972921
[[895   1]
 [ 16 122]]
0.991869918699187
